### ISSUE TITLE
Update PMD

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-pmd#27]
Details:

Now that the [ApexMetrics plugin](https://github.com/rsoesemann/codeclimate-apexmetrics
) is discontinued, a customer would like to use an updated version of PMD.

---

- PMD should be used in place of ApexMetrics.
- Additional context: https://github.com/codeclimate/codeclimate-pmd/issues/26

---

- We are currently running [6.0.1](https://github.com/codeclimate/codeclimate-pmd/blob/master/bin/install-pmd.sh#L7)
- the latest available version is [6.6.0](https://github.com/pmd/pmd/releases)

**Comment by larkinscott** [comment]
@efueger I updated PMD to the latest version here: https://github.com/codeclimate/codeclimate-pmd/pull/28

**Comment by efueger** [comment]
Great! I was looking at this earlier today.

Thanks 👍
